# Generated by Django 3.2.7 on 2021-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('MERCEDES', 'Mercedes'), ('TESLA', 'Tesla'), ('BMW', 'Bmw'), ('AUDI', 'Audi')], max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
    ]
